package types

type HVAC struct {
	ActionTemplate string `json:"action_template,omitempty"`
	ActionTopic string `json:"action_topic,omitempty"`
	AuxCommandTopic string `json:"aux_command_topic,omitempty"`
	AuxStateTemplate string `json:"aux_state_template,omitempty"`
	AuxStateTopic string `json:"aux_state_topic,omitempty"`
	Availability []Availability `json:"availability,omitempty"`
	AvailabilityMode string `json:"availability_mode,omitempty"`
	AvailabilityTopic string `json:"availability_topic,omitempty"`
	AwayModeCommandTopic string `json:"away_mode_command_topic,omitempty"`
	AwayModeStateTemplate string `json:"away_mode_state_template,omitempty"`
	AwayModeStateTopic string `json:"away_mode_state_topic,omitempty"`
	CurrentTemperatureTemplate string `json:"current_temperature_template,omitempty"`
	CurrentTemperatureTopic string `json:"current_temperature_topic,omitempty"`
	Device Device `json:"device,omitempty"`
	EnabledByDefault bool `json:"enabled_by_default,omitempty"`
	EntityCategory EntityCategory `json:"entity_category,omitempty"`
	FanModeCommandTemplate string `json:"fan_mode_command_template,omitempty"`
	FanModeCommandTopic string `json:"fan_mode_command_topic,omitempty"`
	FanModeStateTemplate string `json:"fan_mode_state_template,omitempty"`
	FanModeStateTopic string `json:"fan_mode_state_topic,omitempty"`
	FanModes []string `json:"fan_modes,omitempty"`
	HoldCommandTemplate string `json:"hold_command_template,omitempty"`
	HoldCommandTopic string `json:"hold_command_topic,omitempty"`
	HoldStateTemplate string `json:"hold_state_template,omitempty"`
	HoldStateTopic string `json:"hold_state_topic,omitempty"`
	HoldModes []string `json:"hold_modes,omitempty"`
	Initial int `json:"initial,omitempty"`
	Icon string `json:"icon,omitempty"`
	JSONAttributesTemplate string `json:"json_attributes_template,omitempty"`
	JSONAttributesTopic string `json:"json_attributes_topic,omitempty"`
	MaxTemp float32 `json:"max_temp,omitempty"`
	MinTemp float32 `json:"min_temp,omitempty"`
	ModeCommandTemplate string `json:"mode_command_template,omitempty"`
	ModeCommandTopic string `json:"mode_command_topic,omitempty"`
	ModeStateTemplate string `json:"mode_state_template,omitempty"`
	ModeStateTopic string `json:"mode_state_topic,omitempty"`
	Modes []string `json:"modes,omitempty"`
	Name string `json:"name,omitempty"`
	PayloadAvailable string `json:"payload_available,omitempty"`
	PayloadNotAvailable string `json:"payload_not_available,omitempty"`
	PayloadOff string `json:"payload_off,omitempty"`
	PayloadOn string `json:"payload_on,omitempty"`
	PowerCommandTopic string `json:"power_command_topic,omitempty"`
	Precision float32 `json:"precision,omitempty"`
	Qos int `json:"qos,omitempty"`
	Retain bool `json:"retain,omitempty"`
	SendIfOff bool `json:"send_if_off,omitempty"`
	SwingModeCommandTemplate string `json:"swing_mode_command_template,omitempty"`
	SwingModeCommandTopic string `json:"swing_mode_command_topic,omitempty"`
	SwingModeStateTemplate string `json:"swing_mode_state_template,omitempty"`
	SwingModeStateTopic string `json:"swing_mode_state_topic,omitempty"`
	SwingModes []string `json:"swing_modes,omitempty"`
	TemperatureCommandTemplate string `json:"temperature_command_template,omitempty"`
	TemperatureCommandTopic string `json:"temperature_command_topic,omitempty"`
	TemperatureHighCommandTemplate string `json:"temperature_high_command_template,omitempty"`
	TemperatureHighCommandTopic string `json:"temperature_high_command_topic,omitempty"`
	TemperatureHighStateTemplate string `json:"temperature_high_state_template,omitempty"`
	TemperatureHighStateTopic string `json:"temperature_high_state_topic,omitempty"`
	TemperatureLowCommandTemplate string `json:"temperature_low_command_template,omitempty"`
	TemperatureLowCommandTopic string `json:"temperature_low_command_topic,omitempty"`
	TemperatureLowStateTemplate string `json:"temperature_low_state_template,omitempty"`
	TemperatureLowStateTopic string `json:"temperature_low_state_topic,omitempty"`
	TemperatureStateTemplate string `json:"temperature_state_template,omitempty"`
	TemperatureStateTopic string `json:"temperature_state_topic,omitempty"`
	TemperatureUnit string `json:"temperature_unit,omitempty"`
	TempStep float32 `json:"temp_step,omitempty"`
	UniqueID string `json:"unique_id,omitempty"`
	ValueTemplate string `json:"value_template,omitempty"`
}

